{
  imports = [
    ./network
    ./users
    ./home-manager.nix
    ./allow-unfree.nix
    ./gaming.nix
    ./pipewire.nix
    ./plymouth.nix
    ./rip2.nix
    ./stylix.nix
    ./greetd.nix
    ./kernel.nix
    ./cachix.nix
    ./store.nix
    ./droidcam.nix
    ./tablet.nix
    ./zsh.nix
    ./impermenance.nix
    ./nvidia.nix
    ./sops.nix
    ./sudo.nix
    ./lanzaboote.nix
  ];
}
